
github:
  description: Apache SkyWalking CLI
  homepage: https://skywalking.apache.org/
  labels:
    - skywalking
    - observability
    - apm
    - distributed-tracing
    - cli
  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  false
