name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Check License
        uses: apache/skywalking-eyes@main

      - name: Check code generation
        run: make check-codegen
        
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: check-diff
          path: /tmp/swctl/check.diff

      - name: Check License
        run: make license

      - name: Get dependencies
        run: make deps

      - name: Lint
        run: make lint

      - name: Test and report coverage
        run: make coverage

      - name: Build
        run: make build -j3

      - name: Test commands
        run: make test-commands
